name: fashion_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.1.0
  flutter_vector_icons: ^2.0.0
  cross_connectivity: ^3.2.0
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_hooks: ^0.20.5
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.3
  get_storage: ^2.1.1
  page_view_dot_indicator: ^2.3.0
  flutter_otp_text_field: ^1.1.3+2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_wkwebview: ^3.14.0
  webview_universal: ^0.0.5
  # google_maps_flutter: ^2.9.0
  get_time_ago: ^1.3.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.2
  firebase_core: ^2.24.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env.development
    - .env.production
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
